# Generated by Django 3.1.6 on 2021-02-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regalo',
            name='nombre_juguete',
        ),
    ]
